DROP TABLE if EXISTS repository CASCADE;
DROP TABLE if EXISTS secret CASCADE;

CREATE TABLE repository
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url      VARCHAR(max)                              NOT NULL,
    CONSTRAINT repository_url_uk UNIQUE (url),
    PRIMARY KEY (id)
);

CREATE TABLE secret
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    secret      VARCHAR(255)                              NOT NULL,
    repository_id BIGINT NOT NULL,
    CONSTRAINT SECRET_REPOSITORY_REPOSITORY_ID_fk FOREIGN KEY (repository_id) REFERENCES REPOSITORY,
    PRIMARY KEY (id)
);
